//You will need to generate new hps.h file when you assign the address base in Platform designer(Qsys) address mapping before compiling src.c//


#ifndef _ALTERA_HPS_H_
#define _ALTERA_HPS_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'enc3', class 'altera_avalon_pio'
 * The macros are prefixed with 'ENC3_'.
 * The prefix is the slave descriptor.
 */
#define ENC3_COMPONENT_TYPE altera_avalon_pio
#define ENC3_COMPONENT_NAME enc3
#define ENC3_BASE 0x0
#define ENC3_SPAN 16
#define ENC3_END 0xf
#define ENC3_BIT_CLEARING_EDGE_REGISTER 0
#define ENC3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ENC3_CAPTURE 0
#define ENC3_DATA_WIDTH 32
#define ENC3_DO_TEST_BENCH_WIRING 0
#define ENC3_DRIVEN_SIM_VALUE 0
#define ENC3_EDGE_TYPE NONE
#define ENC3_FREQ 50000000
#define ENC3_HAS_IN 1
#define ENC3_HAS_OUT 0
#define ENC3_HAS_TRI 0
#define ENC3_IRQ_TYPE NONE
#define ENC3_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1765748260

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8

/*
 * Macros for device 'key1', class 'altera_avalon_pio'
 * The macros are prefixed with 'KEY1_'.
 * The prefix is the slave descriptor.
 */
#define KEY1_COMPONENT_TYPE altera_avalon_pio
#define KEY1_COMPONENT_NAME key1
#define KEY1_BASE 0x40000
#define KEY1_SPAN 16
#define KEY1_END 0x4000f
#define KEY1_BIT_CLEARING_EDGE_REGISTER 0
#define KEY1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY1_CAPTURE 0
#define KEY1_DATA_WIDTH 32
#define KEY1_DO_TEST_BENCH_WIRING 0
#define KEY1_DRIVEN_SIM_VALUE 0
#define KEY1_EDGE_TYPE NONE
#define KEY1_FREQ 50000000
#define KEY1_HAS_IN 0
#define KEY1_HAS_OUT 1
#define KEY1_HAS_TRI 0
#define KEY1_IRQ_TYPE NONE
#define KEY1_RESET_VALUE 0

/*
 * Macros for device 'key2', class 'altera_avalon_pio'
 * The macros are prefixed with 'KEY2_'.
 * The prefix is the slave descriptor.
 */
#define KEY2_COMPONENT_TYPE altera_avalon_pio
#define KEY2_COMPONENT_NAME key2
#define KEY2_BASE 0x50000
#define KEY2_SPAN 16
#define KEY2_END 0x5000f
#define KEY2_BIT_CLEARING_EDGE_REGISTER 0
#define KEY2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY2_CAPTURE 0
#define KEY2_DATA_WIDTH 32
#define KEY2_DO_TEST_BENCH_WIRING 0
#define KEY2_DRIVEN_SIM_VALUE 0
#define KEY2_EDGE_TYPE NONE
#define KEY2_FREQ 50000000
#define KEY2_HAS_IN 0
#define KEY2_HAS_OUT 1
#define KEY2_HAS_TRI 0
#define KEY2_IRQ_TYPE NONE
#define KEY2_RESET_VALUE 0

/*
 * Macros for device 'key3', class 'altera_avalon_pio'
 * The macros are prefixed with 'KEY3_'.
 * The prefix is the slave descriptor.
 */
#define KEY3_COMPONENT_TYPE altera_avalon_pio
#define KEY3_COMPONENT_NAME key3
#define KEY3_BASE 0x60000
#define KEY3_SPAN 16
#define KEY3_END 0x6000f
#define KEY3_BIT_CLEARING_EDGE_REGISTER 0
#define KEY3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY3_CAPTURE 0
#define KEY3_DATA_WIDTH 32
#define KEY3_DO_TEST_BENCH_WIRING 0
#define KEY3_DRIVEN_SIM_VALUE 0
#define KEY3_EDGE_TYPE NONE
#define KEY3_FREQ 50000000
#define KEY3_HAS_IN 0
#define KEY3_HAS_OUT 1
#define KEY3_HAS_TRI 0
#define KEY3_IRQ_TYPE NONE
#define KEY3_RESET_VALUE 0

/*
 * Macros for device 'in0', class 'altera_avalon_pio'
 * The macros are prefixed with 'IN0_'.
 * The prefix is the slave descriptor.
 */
#define IN0_COMPONENT_TYPE altera_avalon_pio
#define IN0_COMPONENT_NAME in0
#define IN0_BASE 0x70000
#define IN0_SPAN 16
#define IN0_END 0x7000f
#define IN0_BIT_CLEARING_EDGE_REGISTER 0
#define IN0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define IN0_CAPTURE 0
#define IN0_DATA_WIDTH 32
#define IN0_DO_TEST_BENCH_WIRING 0
#define IN0_DRIVEN_SIM_VALUE 0
#define IN0_EDGE_TYPE NONE
#define IN0_FREQ 50000000
#define IN0_HAS_IN 0
#define IN0_HAS_OUT 1
#define IN0_HAS_TRI 0
#define IN0_IRQ_TYPE NONE
#define IN0_RESET_VALUE 0

/*
 * Macros for device 'in1', class 'altera_avalon_pio'
 * The macros are prefixed with 'IN1_'.
 * The prefix is the slave descriptor.
 */
#define IN1_COMPONENT_TYPE altera_avalon_pio
#define IN1_COMPONENT_NAME in1
#define IN1_BASE 0x80000
#define IN1_SPAN 16
#define IN1_END 0x8000f
#define IN1_BIT_CLEARING_EDGE_REGISTER 0
#define IN1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define IN1_CAPTURE 0
#define IN1_DATA_WIDTH 32
#define IN1_DO_TEST_BENCH_WIRING 0
#define IN1_DRIVEN_SIM_VALUE 0
#define IN1_EDGE_TYPE NONE
#define IN1_FREQ 50000000
#define IN1_HAS_IN 0
#define IN1_HAS_OUT 1
#define IN1_HAS_TRI 0
#define IN1_IRQ_TYPE NONE
#define IN1_RESET_VALUE 0

/*
 * Macros for device 'key0', class 'altera_avalon_pio'
 * The macros are prefixed with 'KEY0_'.
 * The prefix is the slave descriptor.
 */
#define KEY0_COMPONENT_TYPE altera_avalon_pio
#define KEY0_COMPONENT_NAME key0
#define KEY0_BASE 0x90000
#define KEY0_SPAN 16
#define KEY0_END 0x9000f
#define KEY0_BIT_CLEARING_EDGE_REGISTER 0
#define KEY0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define KEY0_CAPTURE 0
#define KEY0_DATA_WIDTH 32
#define KEY0_DO_TEST_BENCH_WIRING 0
#define KEY0_DRIVEN_SIM_VALUE 0
#define KEY0_EDGE_TYPE NONE
#define KEY0_FREQ 50000000
#define KEY0_HAS_IN 0
#define KEY0_HAS_OUT 1
#define KEY0_HAS_TRI 0
#define KEY0_IRQ_TYPE NONE
#define KEY0_RESET_VALUE 0

/*
 * Macros for device 'in2', class 'altera_avalon_pio'
 * The macros are prefixed with 'IN2_'.
 * The prefix is the slave descriptor.
 */
#define IN2_COMPONENT_TYPE altera_avalon_pio
#define IN2_COMPONENT_NAME in2
#define IN2_BASE 0xa0000
#define IN2_SPAN 16
#define IN2_END 0xa000f
#define IN2_BIT_CLEARING_EDGE_REGISTER 0
#define IN2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define IN2_CAPTURE 0
#define IN2_DATA_WIDTH 32
#define IN2_DO_TEST_BENCH_WIRING 0
#define IN2_DRIVEN_SIM_VALUE 0
#define IN2_EDGE_TYPE NONE
#define IN2_FREQ 50000000
#define IN2_HAS_IN 0
#define IN2_HAS_OUT 1
#define IN2_HAS_TRI 0
#define IN2_IRQ_TYPE NONE
#define IN2_RESET_VALUE 0

/*
 * Macros for device 'in3', class 'altera_avalon_pio'
 * The macros are prefixed with 'IN3_'.
 * The prefix is the slave descriptor.
 */
#define IN3_COMPONENT_TYPE altera_avalon_pio
#define IN3_COMPONENT_NAME in3
#define IN3_BASE 0xb0000
#define IN3_SPAN 16
#define IN3_END 0xb000f
#define IN3_BIT_CLEARING_EDGE_REGISTER 0
#define IN3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define IN3_CAPTURE 0
#define IN3_DATA_WIDTH 32
#define IN3_DO_TEST_BENCH_WIRING 0
#define IN3_DRIVEN_SIM_VALUE 0
#define IN3_EDGE_TYPE NONE
#define IN3_FREQ 50000000
#define IN3_HAS_IN 0
#define IN3_HAS_OUT 1
#define IN3_HAS_TRI 0
#define IN3_IRQ_TYPE NONE
#define IN3_RESET_VALUE 0

/*
 * Macros for device 'enc0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ENC0_'.
 * The prefix is the slave descriptor.
 */
#define ENC0_COMPONENT_TYPE altera_avalon_pio
#define ENC0_COMPONENT_NAME enc0
#define ENC0_BASE 0xc0000
#define ENC0_SPAN 16
#define ENC0_END 0xc000f
#define ENC0_BIT_CLEARING_EDGE_REGISTER 0
#define ENC0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ENC0_CAPTURE 0
#define ENC0_DATA_WIDTH 32
#define ENC0_DO_TEST_BENCH_WIRING 0
#define ENC0_DRIVEN_SIM_VALUE 0
#define ENC0_EDGE_TYPE NONE
#define ENC0_FREQ 50000000
#define ENC0_HAS_IN 1
#define ENC0_HAS_OUT 0
#define ENC0_HAS_TRI 0
#define ENC0_IRQ_TYPE NONE
#define ENC0_RESET_VALUE 0

/*
 * Macros for device 'enc1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ENC1_'.
 * The prefix is the slave descriptor.
 */
#define ENC1_COMPONENT_TYPE altera_avalon_pio
#define ENC1_COMPONENT_NAME enc1
#define ENC1_BASE 0xd0000
#define ENC1_SPAN 16
#define ENC1_END 0xd000f
#define ENC1_BIT_CLEARING_EDGE_REGISTER 0
#define ENC1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ENC1_CAPTURE 0
#define ENC1_DATA_WIDTH 32
#define ENC1_DO_TEST_BENCH_WIRING 0
#define ENC1_DRIVEN_SIM_VALUE 0
#define ENC1_EDGE_TYPE NONE
#define ENC1_FREQ 50000000
#define ENC1_HAS_IN 1
#define ENC1_HAS_OUT 0
#define ENC1_HAS_TRI 0
#define ENC1_IRQ_TYPE NONE
#define ENC1_RESET_VALUE 0

/*
 * Macros for device 'enc2', class 'altera_avalon_pio'
 * The macros are prefixed with 'ENC2_'.
 * The prefix is the slave descriptor.
 */
#define ENC2_COMPONENT_TYPE altera_avalon_pio
#define ENC2_COMPONENT_NAME enc2
#define ENC2_BASE 0xe0000
#define ENC2_SPAN 16
#define ENC2_END 0xe000f
#define ENC2_BIT_CLEARING_EDGE_REGISTER 0
#define ENC2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ENC2_CAPTURE 0
#define ENC2_DATA_WIDTH 32
#define ENC2_DO_TEST_BENCH_WIRING 0
#define ENC2_DRIVEN_SIM_VALUE 0
#define ENC2_EDGE_TYPE NONE
#define ENC2_FREQ 50000000
#define ENC2_HAS_IN 1
#define ENC2_HAS_OUT 0
#define ENC2_HAS_TRI 0
#define ENC2_IRQ_TYPE NONE
#define ENC2_RESET_VALUE 0

/*
 * Macros for device 'Ctrl', class 'altera_avalon_pio'
 * The macros are prefixed with 'CTRL_'.
 * The prefix is the slave descriptor.
 */
#define CTRL_COMPONENT_TYPE altera_avalon_pio
#define CTRL_COMPONENT_NAME Ctrl
#define CTRL_BASE 0xf0000
#define CTRL_SPAN 16
#define CTRL_END 0xf000f
#define CTRL_BIT_CLEARING_EDGE_REGISTER 0
#define CTRL_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CTRL_CAPTURE 0
#define CTRL_DATA_WIDTH 32
#define CTRL_DO_TEST_BENCH_WIRING 0
#define CTRL_DRIVEN_SIM_VALUE 0
#define CTRL_EDGE_TYPE NONE
#define CTRL_FREQ 50000000
#define CTRL_HAS_IN 0
#define CTRL_HAS_OUT 1
#define CTRL_HAS_TRI 0
#define CTRL_IRQ_TYPE NONE
#define CTRL_RESET_VALUE 0

/*
 * Macros for device 'Status', class 'altera_avalon_pio'
 * The macros are prefixed with 'STATUS_'.
 * The prefix is the slave descriptor.
 */
#define STATUS_COMPONENT_TYPE altera_avalon_pio
#define STATUS_COMPONENT_NAME Status
#define STATUS_BASE 0x100000
#define STATUS_SPAN 16
#define STATUS_END 0x10000f
#define STATUS_BIT_CLEARING_EDGE_REGISTER 0
#define STATUS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define STATUS_CAPTURE 0
#define STATUS_DATA_WIDTH 32
#define STATUS_DO_TEST_BENCH_WIRING 0
#define STATUS_DRIVEN_SIM_VALUE 0
#define STATUS_EDGE_TYPE NONE
#define STATUS_FREQ 50000000
#define STATUS_HAS_IN 1
#define STATUS_HAS_OUT 0
#define STATUS_HAS_TRI 0
#define STATUS_IRQ_TYPE NONE
#define STATUS_RESET_VALUE 0


#endif /* _ALTERA_HPS_H_ */

